[platformio]
default_envs = card_emulation_wifi
src_dir = .

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -I src
  -DST25R3916_PIN_MOSI=23
  -DST25R3916_PIN_MISO=19
  -DST25R3916_PIN_SCK=18
  -DST25R3916_PIN_CS=5
  -DST25R3916_PIN_IRQ=2
  -DST25R3916_PIN_SDA=21
  -DST25R3916_PIN_SCL=22
  -DMCU_LED6=14
  -DMCU_LED1=4

[env:card_emulation]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation.cpp>

[env:card_emulation_t4t]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation_t4t.cpp>

[env:card_emulation_t3t]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation_t3t.cpp>

[env:card_emulation_wifi]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation_wifi.cpp>

[env:card_emulation_wifi_f]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
  -DCE_WIFI_NFCF_ONLY
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation_wifi.cpp>

[env:card_emulation_wifi_mixed]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
  -DCE_WIFI_MIXED_TECHS
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/card_emulation_wifi.cpp>

[env:polling]
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/polling.cpp>

[env:cap_sense_mode_switch]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/cap_sense_mode_switch.cpp>

[env:cap_sense_mode_switch_i2c]
build_flags =
  ${env.build_flags}
  -DRFAL_CE_DEBUG
  -DST25R3916_USE_I2C=1
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/cap_sense_mode_switch.cpp>

[env:ndef_rw]
build_src_filter =
  -<*>
  +<src/*.cpp>
  +<pio_src/ndef_rw.cpp>
